// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8A2Z9lM9f7eXStO_2LRGIYyrT_ZVrpaE',
    appId: '1:3361259528:web:a14ed888b110d85924d1bd',
    messagingSenderId: '3361259528',
    projectId: 'socialledger-d0a40',
    authDomain: 'socialledger-d0a40.firebaseapp.com',
    databaseURL: 'https://socialledger-d0a40-default-rtdb.firebaseio.com',
    storageBucket: 'socialledger-d0a40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9x7VEPtWq5pga8tH3oUDEN0fVGG5rvqY',
    appId: '1:3361259528:android:d68ea724be791e2f24d1bd',
    messagingSenderId: '3361259528',
    projectId: 'socialledger-d0a40',
    databaseURL: 'https://socialledger-d0a40-default-rtdb.firebaseio.com',
    storageBucket: 'socialledger-d0a40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJa3Rxw30wZqTI4tG_JoX1txISAL-S_IA',
    appId: '1:3361259528:ios:28290306fc3c157024d1bd',
    messagingSenderId: '3361259528',
    projectId: 'socialledger-d0a40',
    databaseURL: 'https://socialledger-d0a40-default-rtdb.firebaseio.com',
    storageBucket: 'socialledger-d0a40.firebasestorage.app',
    androidClientId: '3361259528-b0geft73qpo328ga0d5h7bqd70pha8nk.apps.googleusercontent.com',
    iosClientId: '3361259528-vrggt4msf5l5kllf1t8afcq7ho0546j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialledgerNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJa3Rxw30wZqTI4tG_JoX1txISAL-S_IA',
    appId: '1:3361259528:ios:28290306fc3c157024d1bd',
    messagingSenderId: '3361259528',
    projectId: 'socialledger-d0a40',
    databaseURL: 'https://socialledger-d0a40-default-rtdb.firebaseio.com',
    storageBucket: 'socialledger-d0a40.firebasestorage.app',
    androidClientId: '3361259528-b0geft73qpo328ga0d5h7bqd70pha8nk.apps.googleusercontent.com',
    iosClientId: '3361259528-vrggt4msf5l5kllf1t8afcq7ho0546j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialledgerNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8A2Z9lM9f7eXStO_2LRGIYyrT_ZVrpaE',
    appId: '1:3361259528:web:d11c29b44b0b3cb424d1bd',
    messagingSenderId: '3361259528',
    projectId: 'socialledger-d0a40',
    authDomain: 'socialledger-d0a40.firebaseapp.com',
    databaseURL: 'https://socialledger-d0a40-default-rtdb.firebaseio.com',
    storageBucket: 'socialledger-d0a40.firebasestorage.app',
  );

}